// Database types - these will be auto-generated by Supabase CLI later
// For now, manual types based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      allowed_users: {
        Row: {
          email: string
          added_by: string | null
          added_at: string
          role: 'admin' | 'user'
        }
        Insert: {
          email: string
          added_by?: string | null
          added_at?: string
          role?: 'admin' | 'user'
        }
        Update: {
          email?: string
          added_by?: string | null
          added_at?: string
          role?: 'admin' | 'user'
        }
      }
      textbooks: {
        Row: {
          id: string
          user_id: string
          title: string
          pdf_url: string | null
          total_pages: number
          metadata: Json | null
          created_at: string
          processing_status: 'pending' | 'processing' | 'completed' | 'failed'
          processing_progress: number
          processing_started_at: string | null
          processing_completed_at: string | null
          processing_error: string | null
          ai_processing_status: 'pending' | 'processing' | 'completed' | 'failed'
          ai_processing_progress: number
          ai_processing_started_at: string | null
          ai_processing_completed_at: string | null
          ai_processing_error: string | null
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          pdf_url?: string | null
          total_pages?: number
          metadata?: Json | null
          created_at?: string
          processing_status?: 'pending' | 'processing' | 'completed' | 'failed'
          processing_progress?: number
          processing_started_at?: string | null
          processing_completed_at?: string | null
          processing_error?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          pdf_url?: string | null
          total_pages?: number
          metadata?: Json | null
          created_at?: string
        }
      }
      pages: {
        Row: {
          id: string
          textbook_id: string
          page_number: number
          raw_text: string
          processed: boolean
          created_at: string
        }
        Insert: {
          id?: string
          textbook_id: string
          page_number: number
          raw_text: string
          processed?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          textbook_id?: string
          page_number?: number
          raw_text?: string
          processed?: boolean
          created_at?: string
        }
      }
      ai_processed_content: {
        Row: {
          id: string
          page_id: string
          summary: string | null
          key_concepts: Json | null
          connections_to_previous: Json | null
          applications: Json | null
          practice_questions: Json | null
          generated_at: string
        }
        Insert: {
          id?: string
          page_id: string
          summary?: string | null
          key_concepts?: Json | null
          connections_to_previous?: Json | null
          applications?: Json | null
          practice_questions?: Json | null
          generated_at?: string
        }
        Update: {
          id?: string
          page_id?: string
          summary?: string | null
          key_concepts?: Json | null
          connections_to_previous?: Json | null
          applications?: Json | null
          practice_questions?: Json | null
          generated_at?: string
        }
      }
      user_notes: {
        Row: {
          id: string
          user_id: string
          textbook_id: string
          page_number: number | null
          content: string
          position: Json | null
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          textbook_id: string
          page_number?: number | null
          content: string
          position?: Json | null
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          textbook_id?: string
          page_number?: number | null
          content?: string
          position?: Json | null
          updated_at?: string
        }
      }
      chat_conversations: {
        Row: {
          id: string
          user_id: string
          textbook_id: string
          context_pages: number[]
          messages: Json
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          textbook_id: string
          context_pages?: number[]
          messages?: Json
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          textbook_id?: string
          context_pages?: number[]
          messages?: Json
          updated_at?: string
        }
      }
      user_preferences: {
        Row: {
          user_id: string
          learning_goals: string | null
          target_level: 'beginner' | 'intermediate' | 'advanced'
          preferred_summary_style: 'concise' | 'detailed' | 'bullet-points'
          ai_personality: string | null
          updated_at: string
        }
        Insert: {
          user_id: string
          learning_goals?: string | null
          target_level?: 'beginner' | 'intermediate' | 'advanced'
          preferred_summary_style?: 'concise' | 'detailed' | 'bullet-points'
          ai_personality?: string | null
          updated_at?: string
        }
        Update: {
          user_id?: string
          learning_goals?: string | null
          target_level?: 'beginner' | 'intermediate' | 'advanced'
          preferred_summary_style?: 'concise' | 'detailed' | 'bullet-points'
          ai_personality?: string | null
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'admin' | 'user'
      target_level: 'beginner' | 'intermediate' | 'advanced'
      summary_style: 'concise' | 'detailed' | 'bullet-points'
    }
  }
}

